<a href="https://colab.research.google.com/github/DanielGardS/coursePython/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [ ]:
url = 'https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv'
np.loadtxt(url, delimiter=',')

ValueError: could not convert string '' to float64 at row 0, column 1.

In [5]:
#En el data set de las manzanas se puede ver que la primer columna es null además que en la siguientes esta el nombre de las ciudades
#Como  no se ocupará es mejor crear un arreglo de los meses para iterar
#12 *7 +3 #doce meses por siete años y tres meses total de 87 meses
columnas=np.arange(1,88,1)
#print(columnas)

In [27]:
url = 'https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv'
datos = np.loadtxt(url, delimiter=',',usecols=columnas)

In [7]:
#Explicación intermedia
import numpy as np

# crea una lista
lista = [1, 2, 3, 4, 5]

# convierte la lista en un array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)

Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


In [8]:
#comparación tiempo de procesamiento entre lista y array Numpy
import numpy as np
import time

# crea una lista con 1000000 elementos
lista = list(range(1000000))

# convierte la lista en un array Numpy
array = np.array(lista)

# comienza a medir el tiempo para la operación con la lista
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento de la lista
lista_cuadrado = [i**2 for i in lista]

# detiene el cronómetro
tiempo_lista = time.time() - start_time

# comienza a medir el tiempo para la operación con el array
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento del array
array_cuadrado = array**2

# detiene el cronómetro
tiempo_array = time.time() - start_time

print("Tiempo de la operación con la lista: ", tiempo_lista)
print("Tiempo de la operación con el array: ", tiempo_array)

Tiempo de la operación con la lista:  0.07990527153015137
Tiempo de la operación con el array:  0.006613492965698242


In [28]:
#Manipulando la información del csv de
datos
#Identificar la cantidad de dimensiones
datos.ndim
#Cuantas columnas y filas
datos.shape
#Convertir las filas en columnas trasnponer
datos_transpuesto=datos.T
datos_transpuesto

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

Ha llegado el momento de poner a prueba los conocimientos adquiridos durante la lección. Para ello, vamos a utilizar otro conjunto de datos en un desafío que se desarrollará a lo largo del curso. Este conjunto de datos es una versión modificada del archivo disponible en el sitio de Kaggle. https://www.kaggle.com/datasets/joshmcadams/oranges-vs-grapefruit
Por lo tanto, utilizaremos el archivo raw disponible en Github.

https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv

En esta etapa, debes cargar los datos. Para hacerlo, importa NumPy y utiliza la función loadtxt. Utiliza el enlace de la URL y el parámetro usecols para omitir la primera columna. Puedes usar np.arange para crear la secuencia de números que representan las columnas. Por último, también es necesario incluir el parámetro skiprows=1 para que la primera línea de texto se omita al leer el archivo.

In [24]:
import numpy as np
url2 ='https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv'
datos2 = np.loadtxt(url2, delimiter=',',skiprows=1, usecols=np.arange(1,6,1))
datos2

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [25]:
import numpy as np
url2 ='https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv'
datos = np.loadtxt(url2, delimiter=',', usecols=np.arange(1,6,1),skiprows=1)
datos

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

**Visualización y Selección**

In [29]:
#Obtener todas las fechas para eso se recorren la matriz primero todas las filas y despues las columnas
fechas = datos_transpuesto [:,0] # Los dos puntos trae todas las filas
fechas

array([ 1.2013,  2.2013,  3.2013,  4.2013,  5.2013,  6.2013,  7.2013,
        8.2013,  9.2013, 10.2013, 11.2013, 12.2013,  1.2014,  2.2014,
        3.2014,  4.2014,  5.2014,  6.2014,  7.2014,  8.2014,  9.2014,
       10.2014, 11.2014, 12.2014,  1.2015,  2.2015,  3.2015,  4.2015,
        5.2015,  6.2015,  7.2015,  8.2015,  9.2015, 10.2015, 11.2015,
       12.2015,  1.2016,  2.2016,  3.2016,  4.2016,  5.2016,  6.2016,
        7.2016,  8.2016,  9.2016, 10.2016, 11.2016, 12.2016,  1.2017,
        2.2017,  3.2017,  4.2017,  5.2017,  6.2017,  7.2017,  8.2017,
        9.2017, 10.2017, 11.2017, 12.2017,  1.2018,  2.2018,  3.2018,
        4.2018,  5.2018,  6.2018,  7.2018,  8.2018,  9.2018, 10.2018,
       11.2018, 12.2018,  1.2019,  2.2019,  3.2019,  4.2019,  5.2019,
        6.2019,  7.2019,  8.2019,  9.2019, 10.2019, 11.2019, 12.2019,
        1.202 ,  2.202 ,  3.202 ])

In [30]:
#Obtener los precios de la manzanas
precios = datos_transpuesto [:, 1:] # Para iterar sobre las columnas 1 a 6 se puede dejar solo los dos puntos pues se incluyen
precios

array([[ 79.72,  42.67,  62.55,  48.26,  71.25],
       [ 81.08,  44.37,  62.73,  51.01,  71.35],
       [ 79.68,  44.73,  63.43,  50.91,  70.9 ],
       [ 79.8 ,  46.75,  63.83,  53.94,  71.92],
       [ 80.63,    nan,  66.06,  61.27,  72.91],
       [ 80.8 ,  51.59,  69.22,  65.44,  74.39],
       [ 80.28,  57.8 ,  72.07,  56.51,  73.1 ],
       [ 78.99,  62.14,  69.31,  53.  ,  70.24],
       [ 76.77,  56.76,  65.18,  43.87,  69.12],
       [ 76.09,  50.85,  62.13,  42.12,  68.98],
       [ 76.36,  46.43,  64.17,  43.98,  68.58],
       [ 77.16,  46.73,  65.5 ,  44.66,  69.5 ],
       [ 77.5 ,  45.85,  66.85,  47.73,  70.14],
       [ 79.03,  49.25,  68.38,  52.31,  70.58],
       [ 80.28,  48.14,  68.77,  56.8 ,  70.78],
       [ 80.05,  49.18,  69.32,  51.15,  72.78],
       [ 78.11,  49.49,  69.77,  54.63,  72.84],
       [ 76.9 ,  49.83,  70.17,  55.8 ,  74.74],
       [ 77.68,  49.14,  70.76,  57.31,  76.43],
       [ 76.05,  63.21,  75.16,  53.81,  81.2 ],
       [ 75.53,  61.